version: '3'
services:

  pangolin-db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    image: pangolin-db
    container_name: pangolin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: pangolin
    ports:
      - '5432:5432'  

