version: '3'
services:

  pangolin-db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    image: pangolin-db
    container_name: pangolin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: pangolin
    ports:
      - '5432:5432'

  pangolin-db-test:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: pangolin-db
    container_name: pangolin-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: pangolin-test
      PANGOLIN_ADMIN_PASSWORD: ${PANGOLIN_ADMIN_PASSWORD}
    ports:
      - '5431:5432'

